translations = {
    "es": {
        "select_language": "Selecciona el idioma",
        "accept_disclaimer": "Aceptar",
        "disclaimer_text": "Esta aplicación tiene fines educativos y no reemplaza el diagnóstico médico profesional.",
        "ecg_report_title": "Informe de ECG",
        "ecg_report_body": "Este informe fue generado por una herramienta de inteligencia artificial con fines educativos. No reemplaza la interpretación médica profesional.",
        "report_footer": "Informe generado por IA con fines educativos. No reemplaza la opinión médica profesional."
    },
    "en": {
        "select_language": "Select language",
        "accept_disclaimer": "Accept",
        "disclaimer_text": "This application is for educational purposes only and does not replace professional medical diagnosis.",
        "ecg_report_title": "EKG Report",
        "ecg_report_body": "This report was generated by an AI tool for educational purposes. It does not replace professional medical interpretation.",
        "report_footer": "Report generated by AI for educational purposes. Does not replace professional medical opinion."
    },
    "fr": {
        "select_language": "Choisir la langue",
        "accept_disclaimer": "Accepter",
        "disclaimer_text": "Cette application est à des fins éducatives et ne remplace pas un diagnostic médical professionnel.",
        "ecg_report_title": "Rapport ECG",
        "ecg_report_body": "Ce rapport a été généré par un outil d'intelligence artificielle à des fins éducatives. Il ne remplace pas une interprétation médicale professionnelle.",
        "report_footer": "Rapport généré par l'IA à des fins éducatives. Ne remplace pas un avis médical professionnel."
    },
    "it": {
        "select_language": "Seleziona la lingua",
        "accept_disclaimer": "Accetta",
        "disclaimer_text": "Questa applicazione ha scopi educativi e non sostituisce una diagnosi medica professionale.",
        "ecg_report_title": "Referto ECG",
        "ecg_report_body": "Questo referto è stato generato da uno strumento di intelligenza artificiale a scopo educativo. Non sostituisce l'interpretazione medica professionale.",
        "report_footer": "Referto generato da IA a scopo educativo. Non sostituisce un parere medico professionale."
    },
    "pt": {
        "select_language": "Selecionar idioma",
        "accept_disclaimer": "Aceitar",
        "disclaimer_text": "Este aplicativo é para fins educacionais e não substitui o diagnóstico médico profissional.",
        "ecg_report_title": "Relatório de ECG",
        "ecg_report_body": "Este relatório foi gerado por uma ferramenta de inteligência artificial para fins educacionais. Não substitui a interpretação médica profissional.",
        "report_footer": "Relatório gerado por IA para fins educacionais. Não substitui opinião médica profissional."
    },
    "de": {
        "select_language": "Sprache auswählen",
        "accept_disclaimer": "Akzeptieren",
        "disclaimer_text": "Diese Anwendung dient Bildungszwecken und ersetzt keine professionelle medizinische Diagnose.",
        "ecg_report_title": "EKG-Bericht",
        "ecg_report_body": "Dieser Bericht wurde von einem KI-Tool zu Bildungszwecken erstellt. Er ersetzt keine professionelle medizinische Interpretation.",
        "report_footer": "Bericht von KI zu Bildungszwecken erstellt. Ersetzt keine professionelle medizinische Meinung."
    },
    "ar": {
        "select_language": "اختر اللغة",
        "accept_disclaimer": "أوافق",
        "disclaimer_text": "هذا التطبيق لأغراض تعليمية ولا يحل محل التشخيص الطبي المهني.",
        "ecg_report_title": "تقرير تخطيط القلب",
        "ecg_report_body": "تم إنشاء هذا التقرير بواسطة أداة ذكاء اصطناعي لأغراض تعليمية. لا يحل محل التفسير الطبي المهني.",
        "report_footer": "تم إنشاء التقرير بواسطة الذكاء الاصطناعي لأغراض تعليمية. لا يحل محل الرأي الطبي المهني."
    }
}